version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: "${PWD}/elasticsearch/"
      dockerfile: elastic.Dockerfile
      args:
        VERSION: $ELASTICSEARCH_VERSION
    volumes:
      - type: bind
        source: "${PWD}/elasticsearch/config/elasticsearch.yml"
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      ELASTIC_PASSWORD: $ELASTICSEARCH_PASSWORD
      discovery.type: single-node
    networks:
      - elk-stack

  logstash:
    container_name: logstash
    build:
      context: "${PWD}/logstash/"
      dockerfile: logstash.Dockerfile
      args:
        VERSION: $LOGSTASH_VERSION
    volumes:
      - type: bind
        source: "${PWD}/logstash/config/logstash.yml"
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: "${PWD}/logstash/pipeline"
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5001:5001/tcp"
      - "5001:5001/udp"
      - "5044:5044/tcp"
      - "5044:5044/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk-stack
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: ${PWD}/kibana/
      dockerfile: kibana.Dockerfile
      args:
        VERSION: $KIBANA_VERSION
    volumes:
      - type: bind
        source: "${PWD}/kibana/config/kibana.yml"
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk-stack
    depends_on:
      - elasticsearch

networks:
  elk-stack:
    driver: bridge